# GIT(pokedaemon)
alias gs="git status --short"
alias gd="git diff"
alias ga="git add"
alias gap="git add --patch"
alias gc="git commit"
alias gp="git push"
alias gu="git pull"
alias gl="git log --all --graph --pretty=format:'%C(magenta)%h %C(white) %an  %ar%C(auto)  %D%n%s%n'"
alias gb="git branch"
alias gi="git init"
alias gcl="git clone"
alias gm="git merge"
alias gr="git reset"

# Docker(pokedaemon)
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"'
alias dc="docker compose"
alias dl="docler logs --tail=100"

